version: "3.5"

services:
  isucon5-datagen:
    image: isucon5-datagen/latest
    build:
      context: ./
    container_name: isucon5-datagen
    hostname: isucon5-datagen
    command: >
      bash -c 
        "bundle exec ruby gen.rb help \
         && bundle exec ruby gen.rb gen_users \
         && bundle exec ruby gen.rb gen_entries \
         && bundle exec ruby gen.rb gen_comments \
         && bundle exec ruby gen.rb gen_footprints \
         && bundle exec ruby gen.rb gen_relations \
         && bundle exec ruby gen.rb gen_testsets"
