version: "3.8"

services:
  isucon5-datagen:
    image: isucon5-datagen/latest
    build:
      context: ./
    container_name: isucon5-datagen
    hostname: isucon5-datagen
    environment:
      - ISUCON5Q_DB_HOST=${DB_HOST}
      - ISUCON5Q_DB_PORT=${DB_PORT}
      - ISUCON5Q_DB_NAME=${DB_NAME}
      - ISUCON5Q_DB_USER=${DB_USER}
      - ISUCON5Q_DB_PASSWORD=${DB_PASS}
    command: >
      bash -c 
        "bundle exec ruby gen.rb gen_users \
         && bundle exec ruby gen.rb gen_relations \
         && bundle exec ruby gen.rb gen_entries \
         && bundle exec ruby gen.rb gen_comments \
         && bundle exec ruby gen.rb gen_footprints \
         && bundle exec ruby gen.rb gen_testsets"
