version: "3.8"

services:
  isucon5-portal:
    image: isucon5-eventapp/latest
    build:
      context: ./
    container_name: isucon5-portal
    hostname: isucon5-portal
    depends_on:
      - isucon5-mysql
    ports:
      - "8081:8080"
    volumes:
      - ./data:/isucon5-eventapp/data
    environment:
      - ISUCON5_DB_HOST=${PORTAL_DB_HOST}
      - ISUCON5_DB_PORT=${PORTAL_DB_PORT}
      - ISUCON5_DB_NAME=${PORTAL_DB_NAME}
      - ISUCON5_DB_USER=${PORTAL_DB_USER}
      - ISUCON5_DB_PASSWORD=${PORTAL_DB_PASS}

  isucon5-scores-updater:
    image: isucon5-eventapp/latest
    build:
      context: ./
    container_name: isucon5-scores-updater
    hostname: isucon5-scores-updater
    depends_on:
      - isucon5-mysql
      - isucon5-portal
    environment:
      - ISUCON5_DB_HOST=${PORTAL_DB_HOST}
      - ISUCON5_DB_PORT=${PORTAL_DB_PORT}
      - ISUCON5_DB_NAME=${PORTAL_DB_NAME}
      - ISUCON5_DB_USER=${PORTAL_DB_USER}
      - ISUCON5_DB_PASSWORD=${PORTAL_DB_PASS}
    command: >
      bash -c 
        "bundle exec ruby update_scores.rb"

  isucon5-mysql:
    image: mysql:5.6.51
    container_name: isucon5-mysql
    hostname: isucon5-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${PORTAL_DB_NAME}
      - MYSQL_USER=isucon5_user
      - MYSQL_PASSWORD=user_isucon5
